/**
 * Types for the Alternate History Generator (Melquíades' Prophecy)
 * This feature allows users to explore "what if" scenarios in the Buendía family timeline
 */

/** Category of divergence from the original timeline */
export type DivergenceCategory = 'death' | 'decision' | 'event' | 'relationship';

/** A point where history could have diverged */
export interface DivergencePoint {
  id: string;
  title: string;
  description: string;
  chapter: number;
  characterIds: string[];
  originalOutcome: string;
  category: DivergenceCategory;
}

/** A single butterfly effect - how one character's fate changes */
export interface ButterflyEffect {
  characterId: string;
  characterName: string;
  originalFate: string;
  alternateFate: string;
  cascadeLevel: number; // 1=direct, 2=secondary, 3+=ripple
}

/** A complete alternate timeline generated by Gemini */
export interface AlternateTimeline {
  id: string;
  divergencePoint: DivergencePoint;
  question: string;
  narrative: string;
  effects: ButterflyEffect[];
  thinkingTrace?: string;
  timestamp: Date;
}

/** A preset scenario with suggested question and visual metadata */
export interface PresetScenario extends DivergencePoint {
  suggestedQuestion: string;
  mood: 'hopeful' | 'tragic' | 'melancholic' | 'mysterious' | 'dramatic' | 'bittersweet';
  icon: string;
}
